import type { Exercise } from '@/types/models'

const timestamp = '2026-05-23T14:30:00.000Z'

export const exerciseCatalog: Exercise[] = [
  {
    id: 'squat',
    name: 'Air Squat',
    category: 'legs',
    description: 'Build lower-body strength with controlled depth and stable knee tracking.',
    targetMuscles: ['Quadriceps', 'Glutes', 'Core'],
    difficulty: 'Beginner',
    equipment: ['Bodyweight'],
    formTips: ['Brace your core before descending.', 'Keep your knees aligned with your toes.', 'Drive through your mid-foot to stand tall.'],
    commonMistakes: ['Shallow range of motion', 'Knees caving inward', 'Rounded lower back'],
    caloriesPerMinute: 8,
    suggestedDurationMin: 8,
    suggestedReps: '3 x 12',
    premiumNotes: 'Use a heel-elevated variation if ankle mobility limits depth.',
    previewType: 'demo',
    supportedForRealtime: true,
    updatedAt: timestamp,
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'chest',
    description: 'Classic bodyweight press for chest, shoulders, and trunk stiffness.',
    targetMuscles: ['Chest', 'Triceps', 'Front Delts', 'Core'],
    difficulty: 'Intermediate',
    equipment: ['Bodyweight'],
    formTips: ['Create a straight line from shoulders to heels.', 'Lower until elbows reach at least ninety degrees.', 'Press the floor away evenly.'],
    commonMistakes: ['Hips sagging', 'Elbow flare', 'Partial reps'],
    caloriesPerMinute: 9,
    suggestedDurationMin: 6,
    suggestedReps: '4 x 10',
    premiumNotes: 'Elevate the hands to scale down while preserving range and trunk position.',
    previewType: 'demo',
    supportedForRealtime: true,
    updatedAt: timestamp,
  },
  {
    id: 'lunge',
    name: 'Reverse Lunge',
    category: 'legs',
    description: 'Single-leg strength and balance drill with reduced knee stress.',
    targetMuscles: ['Glutes', 'Quadriceps', 'Hamstrings'],
    difficulty: 'Intermediate',
    equipment: ['Bodyweight'],
    formTips: ['Step back softly and keep your torso stacked over the hips.', 'Front knee tracks over the middle toes.', 'Push through the front heel on the return.'],
    commonMistakes: ['Forward collapse', 'Narrow stance', 'Incomplete depth'],
    caloriesPerMinute: 8,
    suggestedDurationMin: 8,
    suggestedReps: '3 x 10 each side',
    premiumNotes: 'Add a pause at the bottom to improve balance and hip control.',
    previewType: 'demo',
    supportedForRealtime: true,
    updatedAt: timestamp,
  },
  {
    id: 'plank',
    name: 'Forearm Plank',
    category: 'core',
    description: 'Static anti-extension core hold for trunk endurance and postural control.',
    targetMuscles: ['Core', 'Shoulders', 'Glutes'],
    difficulty: 'Beginner',
    equipment: ['Bodyweight'],
    formTips: ['Press the forearms into the floor.', 'Keep your hips level with your shoulders.', 'Breathe slowly and stay long through the crown of the head.'],
    commonMistakes: ['Hips too high', 'Sagging torso', 'Shoulders drifting behind elbows'],
    caloriesPerMinute: 4,
    suggestedDurationMin: 5,
    suggestedReps: '3 x 30 sec',
    premiumNotes: 'Think of zipping your ribs down instead of only squeezing your abs.',
    previewType: 'demo',
    supportedForRealtime: true,
    updatedAt: timestamp,
  },
  {
    id: 'shoulder-press',
    name: 'Shoulder Press',
    category: 'shoulders',
    description: 'Vertical push pattern that rewards smooth overhead mechanics.',
    targetMuscles: ['Deltoids', 'Triceps', 'Upper Back'],
    difficulty: 'Intermediate',
    equipment: ['Dumbbells', 'Resistance Bands'],
    formTips: ['Stack wrists over elbows at the bottom.', 'Finish with biceps near the ears.', 'Keep ribs down during the press.'],
    commonMistakes: ['Overarching the back', 'Uneven lockout', 'Pressing too far forward'],
    caloriesPerMinute: 6,
    suggestedDurationMin: 7,
    suggestedReps: '4 x 8',
    premiumNotes: 'Half-kneeling presses improve pelvic control and shoulder centration.',
    previewType: 'demo',
    supportedForRealtime: true,
    updatedAt: timestamp,
  },
  {
    id: 'bicep-curl',
    name: 'Bicep Curl',
    category: 'arms',
    description: 'Controlled elbow flexion drill that teaches strict arm isolation.',
    targetMuscles: ['Biceps', 'Forearms'],
    difficulty: 'Beginner',
    equipment: ['Dumbbells', 'Resistance Bands'],
    formTips: ['Pin elbows near your ribs.', 'Raise with control and squeeze at the top.', 'Lower slowly for full range.'],
    commonMistakes: ['Swinging the torso', 'Shoulders rolling forward', 'Short range of motion'],
    caloriesPerMinute: 4,
    suggestedDurationMin: 6,
    suggestedReps: '3 x 12',
    premiumNotes: 'Alternating curls can reduce compensation if one side dominates.',
    previewType: 'demo',
    supportedForRealtime: true,
    updatedAt: timestamp,
  },
  {
    id: 'jumping-jack',
    name: 'Jumping Jack',
    category: 'cardio',
    description: 'Light conditioning drill that raises heart rate and coordination.',
    targetMuscles: ['Calves', 'Shoulders', 'Core'],
    difficulty: 'Beginner',
    equipment: ['Bodyweight'],
    formTips: ['Land softly under the hips.', 'Reach overhead with control.', 'Stay springy without slamming the heels.'],
    commonMistakes: ['Short arm reach', 'Feet not opening enough', 'Heavy landings'],
    caloriesPerMinute: 10,
    suggestedDurationMin: 5,
    suggestedReps: '3 x 30 sec',
    premiumNotes: 'Use low-impact step jacks when training in tight spaces or with joint sensitivity.',
    previewType: 'demo',
    supportedForRealtime: true,
    updatedAt: timestamp,
  },
  {
    id: 'cat-cow',
    name: 'Cat-Cow Flow',
    category: 'mobility',
    description: 'Gentle spinal segmentation and breathing reset.',
    targetMuscles: ['Thoracic Spine', 'Core', 'Hips'],
    difficulty: 'Beginner',
    equipment: ['Yoga Mat'],
    formTips: ['Exhale into the rounded cat shape.', 'Inhale as you broaden the chest.', 'Move one vertebra at a time.'],
    commonMistakes: ['Moving too quickly', 'Collapsing the shoulders', 'Holding the breath'],
    caloriesPerMinute: 3,
    suggestedDurationMin: 4,
    suggestedReps: '2 x 8 breaths',
    premiumNotes: 'Use this between strength sets to restore spinal motion and downshift tension.',
    previewType: 'demo',
    supportedForRealtime: true,
    updatedAt: timestamp,
  },
  {
    id: 'hip-hinge',
    name: 'Hip Hinge Drill',
    category: 'mobility',
    description: 'Patterning drill for glute loading and neutral-spine deadlift mechanics.',
    targetMuscles: ['Hamstrings', 'Glutes', 'Lower Back'],
    difficulty: 'Beginner',
    equipment: ['Dowell or Bodyweight'],
    formTips: ['Send the hips back first.', 'Keep the ribs stacked over the pelvis.', 'Maintain a soft bend in the knees.'],
    commonMistakes: ['Excessive knee bend', 'Rounded back', 'Weight shifting to the toes'],
    caloriesPerMinute: 4,
    suggestedDurationMin: 5,
    suggestedReps: '3 x 10',
    premiumNotes: 'Use a wall target behind you to cue backward hip travel.',
    previewType: 'demo',
    supportedForRealtime: true,
    updatedAt: timestamp,
  },
  {
    id: 'sun-salutation',
    name: 'Sun Salutation',
    category: 'yoga',
    description: 'Flow sequence for mobility, breathing, and warm-up readiness.',
    targetMuscles: ['Hamstrings', 'Shoulders', 'Core'],
    difficulty: 'Intermediate',
    equipment: ['Yoga Mat'],
    formTips: ['Coordinate each transition with your breath.', 'Lengthen the spine before folding.', 'Press evenly through the hands in plank.'],
    commonMistakes: ['Rushing transitions', 'Locked knees', 'Holding the breath'],
    caloriesPerMinute: 5,
    suggestedDurationMin: 8,
    suggestedReps: '5 rounds',
    premiumNotes: 'Ideal on recovery days when you still want to protect the streak.',
    previewType: 'demo',
    supportedForRealtime: false,
    updatedAt: timestamp,
  },
]
