import type { WorkoutPlan } from '@/types/models'

const timestamp = '2026-05-23T14:30:00.000Z'

export const workoutPlans: WorkoutPlan[] = [
  {
    id: 'beginner-foundation',
    title: 'Beginner Foundation',
    description: 'Three-day plan focused on movement quality, balance, and adherence.',
    targetLevel: 'Beginner',
    goalType: 'wellness',
    workoutStyle: 'Balanced',
    unlockLevel: 'Beginner',
    estimatedMinutes: 28,
    items: [
      { exerciseId: 'squat', sets: 3, reps: '10', restSeconds: 45 },
      { exerciseId: 'push-up', sets: 3, reps: '8', restSeconds: 45 },
      { exerciseId: 'plank', sets: 3, reps: '30 sec', restSeconds: 30 },
      { exerciseId: 'cat-cow', sets: 2, reps: '8 breaths', restSeconds: 20 },
    ],
    updatedAt: timestamp,
  },
  {
    id: 'fat-loss-sprint',
    title: 'Fat Loss Accelerator',
    description: 'Conditioning-forward circuit with hydration and consistency bonuses.',
    targetLevel: 'Intermediate',
    goalType: 'fat_loss',
    workoutStyle: 'Circuit',
    unlockLevel: 'Intermediate',
    estimatedMinutes: 32,
    items: [
      { exerciseId: 'jumping-jack', sets: 4, reps: '40 sec', restSeconds: 20 },
      { exerciseId: 'squat', sets: 4, reps: '15', restSeconds: 30 },
      { exerciseId: 'lunge', sets: 3, reps: '10 each side', restSeconds: 30 },
      { exerciseId: 'plank', sets: 3, reps: '40 sec', restSeconds: 30 },
    ],
    updatedAt: timestamp,
  },
  {
    id: 'muscle-gain-blueprint',
    title: 'Muscle Gain Blueprint',
    description: 'Progressive overload-focused split with movement coaching.',
    targetLevel: 'Pro',
    goalType: 'muscle_gain',
    workoutStyle: 'Strength',
    unlockLevel: 'Pro',
    estimatedMinutes: 45,
    items: [
      { exerciseId: 'shoulder-press', sets: 4, reps: '8', restSeconds: 75 },
      { exerciseId: 'push-up', sets: 4, reps: '12', restSeconds: 60 },
      { exerciseId: 'bicep-curl', sets: 4, reps: '12', restSeconds: 45 },
      { exerciseId: 'hip-hinge', sets: 3, reps: '12', restSeconds: 45 },
    ],
    updatedAt: timestamp,
  },
  {
    id: 'home-anywhere',
    title: 'Home Anywhere',
    description: 'Zero-equipment plan tuned for small spaces and consistent training.',
    targetLevel: 'Beginner',
    goalType: 'wellness',
    workoutStyle: 'Home',
    unlockLevel: 'Beginner',
    estimatedMinutes: 24,
    items: [
      { exerciseId: 'squat', sets: 3, reps: '15', restSeconds: 30 },
      { exerciseId: 'jumping-jack', sets: 3, reps: '30 sec', restSeconds: 20 },
      { exerciseId: 'push-up', sets: 3, reps: '10', restSeconds: 30 },
      { exerciseId: 'cat-cow', sets: 2, reps: '10 breaths', restSeconds: 20 },
    ],
    updatedAt: timestamp,
  },
  {
    id: 'gym-split-precision',
    title: 'Gym Split Precision',
    description: 'Four-day split with stricter form thresholds and deeper analytics.',
    targetLevel: 'Athlete',
    goalType: 'performance',
    workoutStyle: 'Gym Split',
    unlockLevel: 'Athlete',
    estimatedMinutes: 55,
    items: [
      { exerciseId: 'hip-hinge', sets: 4, reps: '8', restSeconds: 90 },
      { exerciseId: 'shoulder-press', sets: 4, reps: '8', restSeconds: 75 },
      { exerciseId: 'lunge', sets: 4, reps: '8 each side', restSeconds: 45 },
      { exerciseId: 'plank', sets: 3, reps: '60 sec', restSeconds: 45 },
    ],
    updatedAt: timestamp,
  },
]
